Citizen.CreateThread(function()
AddTextEntry("gstbufst1", "Buffalo ST")
AddTextEntry("gstbufst_spoiler1", "A/C Primary Rear Spoiler")
AddTextEntry("gstbufst_spoiler2", "A/C Secondary Rear Spoiler")
AddTextEntry("gstbufst_spoiler3", "A/C Plastic Rear Spoiler")
AddTextEntry("gstbufst_spoiler4", "STX Primary Rear Spoiler")
AddTextEntry("gstbufst_spoiler5", "STX Secondary Rear Spoiler")
AddTextEntry("gstbufst_spoiler6", "STX Plastic Rear Spoiler")
AddTextEntry("gstbufst_spoiler7", "Hellfire Primary Rear Spoiler")
AddTextEntry("gstbufst_spoiler8", "Hellfire Secondary Rear Spoiler")
AddTextEntry("gstbufst_spoiler9", "Hellfire Plastic Rear Spoiler")

AddTextEntry("gstbufst_platerem", "Front Plate Removal")
AddTextEntry("gstbufst_bumf1", "STX Plastic Insert Front Bumper")
AddTextEntry("gstbufst_bumf2", "STX Primary Insert Front Bumper")
AddTextEntry("gstbufst_bumf3", "STX Secondary Insert Front Bumper")
AddTextEntry("gstbufst_bumf4", "STX Plastic Insert Front Bumper W/ Plate")
AddTextEntry("gstbufst_bumf5", "STX Primary Insert Front Bumper W/ Plate")
AddTextEntry("gstbufst_bumf6", "STX Secondary Insert Front Bumper W/ Plate")
AddTextEntry("gstbufst_bumf7", "Hellfire Front Bumper W/ Plastic Inserts")
AddTextEntry("gstbufst_bumf8", "Hellfire Front Bumper W/ Primary Inserts")
AddTextEntry("gstbufst_bumf9", "Hellfire Front Bumper W/ Secondary Inserts")
AddTextEntry("gstbufst_bumf10", "Hellfire Front Bumper W/ Plastic Inserts N Plate")
AddTextEntry("gstbufst_bumf11", "Hellfire Front Bumper W/ Primary Inserts N Plate")
AddTextEntry("gstbufst_bumf12", "Hellfire Front Bumper W/ Secondary Inserts N Plate")

AddTextEntry("gstbufst_bumr1", "STX Primary Rear Bumper")
AddTextEntry("gstbufst_bumr2", "Hellfire Primary Rear Bumper")

AddTextEntry("gstbufst_hood1", "STX Primary Hood")
AddTextEntry("gstbufst_hood2", "STX Secondary Hood")
AddTextEntry("gstbufst_hood3", "STX Plastic Hood")
AddTextEntry("gstbufst_hood4", "STX Extreme Primary Hood")
AddTextEntry("gstbufst_hood5", "STX Extreme Secondary Hood")
AddTextEntry("gstbufst_hood6", "STX Extreme Plastic Hood")

AddTextEntry("gstbufst_skirt1", "STX Sideskirts")

AddTextEntry("gstbufst_grille1", "Primary Grille Insert")
AddTextEntry("gstbufst_grille2", "Secondary Grille Insert")
AddTextEntry("gstbufst_grille3", "Plastic Grille Insert")
AddTextEntry("gstbufst_grille4", "STX Primary Grille Insert")
AddTextEntry("gstbufst_grille5", "STX Secondary Grille Insert")
AddTextEntry("gstbufst_grille6", "STX Plastic Grille Insert")

AddTextEntry("gstbufst_grillebar1", "Primary Grille Big Bar")
AddTextEntry("gstbufst_grillebar2", "Secondary Grille Big Bar")
AddTextEntry("gstbufst_grillebar3", "STX Primary Grille Big Bar")
AddTextEntry("gstbufst_grillebar4", "STX Secondary Grille Big Bar")
AddTextEntry("gstbufst_grillebar5", "STX Plastic Grille Big Bar")

AddTextEntry("gstbufst_exh1", "Hellfire Stock Exhaust")
end)